# FallenKingdom v0.0.1

#############################################
###                MESSAGES               ###
#############################################


# This section is about the '/fk' command.
command-fk:
  # Message sent to the sender when he doesn't have the permission to execute the command.
  no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
  # This section is about the '/fk start' command.
  start:
    # Message sent to the sender when he doesn't have the permission to execute the command.
    no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
    # Message sent to the sender when he's trying to start a game when another one is already started.
    already-started: "&c>> Une partie est déjà en cours."
    # Message sent to the sender when an error occurred while starting a game.
    error: "&c>> Une erreur est survenue lors du lancement de la partie."
  # This section is about the '/fk stop' command.
  stop:
    # Message sent to the sender when he doesn't have the permission to execute the command.
    no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
    # Message sent to the sender when he's trying to stop a game when there is no game running.
    not-started: "&c>> Il n'y a aucune partie en cours."
    # Message sent to the sender when an error occurred while stopping a game.
    error: "&c>> Une erreur est survenue lors du lancement de la partie."
  # This section is about the '/fk pvp' command.
  pvp:
    # Message sent to the sender when he doesn't have the permission to execute the command.
    no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
    # Message sent to the sender when he's trying to enable / disable pvp when no game is running.
    game-not-running: "&c>> La partie n'a pas encore commencé."
    # Message sent to the sender when he's trying to enable pvp when it already is.
    already-enabled: "&c>> Le pvp est déjà activé."
    # Message sent to the sender when he's trying to disable pvp when it already is.
    already-disabled: "&c>> Le pvp est déjà désactivé."
  # This section is about the '/fk assaults' command.
  assaults:
    # Message sent when the sender doesn't have the permission to execute the command.
    no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
    # Message sent to the sender when he's trying to enable / disable assaults when no game is running.
    game-not-running: "&c>> La partie n'a pas encore commencé."
    # Message sent to the sender when he's trying to enable assaults when they already are.
    already-enabled: "&c>> Les assaults sont déjà activés."
    # Message sent to the sender when he's trying to disable assaults when they already are.
    already-disabled: "&c>> Les assaults sont déjà désactivés."
  # This section is about the '/fk team' command.
  team:
    # Message sent to the sender when the targeted player doesn't exist.
    player-not-found: "&c>> Ce joueur n'est pas connecté."
    # Message sent to the sender when the targeted team doesn't exist.
    team-not-found: "&c>> Cette team n'existe pas."
    # This section is about the '/fk team add' command.
    add:
      # Message sent when the targeted player is already in the specified team.
      already-in-team: "&c>> Ce joueur est déjà dans cette équipe."
      # Message sent to the sender when he added a player to a team. You can use the following placeholders:
      # - %player% -> The name of the targeted player.
      # - %team_name% -> The name of the team to which he was added.
      player-added: "&6%player% &ea été &aajouté &eà l'équipe %team_name%&e."
    # This section is about the '/fk team remove' command.
    remove:
      # Message sent when the targeted player is not in the specified team.
      not-in-team: "&c>> Ce joueur n'est pas dans cette équipe."
      # Message sent to the sender when he removed a player from a team. You can use the following placeholders:
      # - %player% -> The name of the targeted player.
      # - %team_name% -> The name of the team from which he was removed.
      player-removed: "&6%player% &ea été &cretiré &ede l'équipe %team_name%&e."


pvp:
  enabled:
    message:
      type: "MESSAGE"
      text: "&6>> &eLe pvp est désormais &aactivé&e."
    title:
      type: "TITLE"
      title: "&ePvP &aactivé"
      subtitle: "&eRestez sur vos gardes !"
  disabled:
    message:
      type: "MESSAGE"
      text: "&6>> &eLe pvp est désormais &cdésactivé&e."
    title:
      type: "TITLE"
      title: "&ePvP &cdésactivé"
      subtitle: "&eReposez vous un peu !"


assaults:
  enabled:
    message:
      type: "MESSAGE"
      text: "&6>> &eLes assaults sont désormais &aautorisés&e."
    title:
      type: "TITLE"
      title: "&eAssaults &aactivés"
      subtitle: "&ePréparez vos armes !"
  disabled:
    message:
      type: "MESSAGE"
      text: "&6>> &eLes assaults sont désormais &cdésactivés&e."
    title:
      type: "TITLE"
      title: "&eAssaults &cdésactivés"
      subtitle: "&eRangez vos armes !"



# This section is about team messages.
team-messages:
  # Message sent to a player when he joins a team.
  join: "&6>> &eVous avez &arejoint &el'équipe %team_name%&e."
  # Message sent to a player when he leaves a team.
  leave: "&6>> &eVous avez &cquitté &el'équipe %team_name%&e."


capture:
  player-start-capture: "&6>> &eVous capturez la base de l'équipe %team_name%."
  player-stop-capture: "&6>> &eVous ne capturez plus la base de l'équipe %team_name%."
  team-base-start-capture: "&6>> &eL'équipe %team_name% &ecapture votre base."
  team-base-stop-capture: "&6>> &eL'équipe %team_name% &ene capture plus votre base."

#############################################
###                CYCLES                 ###
#############################################


waiting-scoreboard:
  title: "&6&lFallenKingdom"
  lines:
    - "&6&m--------------------"
    - " "
    - "&6• &eStatus&6: %state%"
    - "&6• &eJoueurs&6: &e%online_players%&6/&e%max_players%"
    - " "
    - "&6&m--------------------"
  state:
    waiting: "&cEn attente"
    starting: "&aDémarrage"


game-scoreboard:
  title: "&6&lFallenKingdom"
  lines:
    - "&6&m--------------------"
    - " "
    - "&6• &eEquipe&6: %team_name%"
    - " "
    - "&6• &ePvP&6: %pvp_state%"
    - "&6• &eAssaults&6: %assaults_state%"
    - " "
    - "&6• &eTemps de jeu&6: %time%"
    - " "
    - "&6&m--------------------"
  pvp-state:
    enabled: "&a✔"
    disabled: "&c✘"
  assaults-state:
    enabled: "&a✔"
    disabled: "&c✘"
  time:
    use-short-units: true
    format: "%day%%hour%%minute%%second%"
    time-units:
      day: "j"
      hour: "h"
      minute: "m"
      second: "s"


waiting-cycle:
  # All the settings of the cycle.
  settings:
    # The duration is seconds of the lauch period.
    timer-duration: 10
  # All the displays sent during launch period.
  displays:
    10:
      message:
        type: "MESSAGE"
        text: "&eLa partie commence dans &610 secondes&e."
      sound:
        type: "SOUND"
        sound: "NOTE_BASS"
        pitch: 1
    3:
      message:
        type: "MESSAGE"
        text: "&eLa partie commence dans &63 secondes&e."
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 1
      title:
        type: "TITLE"
        subtitle: "&eLa partie commence dans &63"
    2:
      message:
        type: "MESSAGE"
        text: "&eLa partie commence dans &62 secondes&e."
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 1.5
      title:
        type: "TITLE"
        subtitle: "&eLa partie commence dans &62"
    1:
      message:
        type: "MESSAGE"
        text: "&eLa partie commence dans &61 seconde&e."
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 2
      title:
        type: "TITLE"
        subtitle: "&eLa partie commence dans &61"
    0:
      message:
        type: "MESSAGE"
        text: "&eLa partie commence !"
      sound:
        type: "SOUND"
        sound: "LEVEL_UP"
        pitch: 2
      title:
        type: "TITLE"
        subtitle: "&6La partie commence !"
        stay: 20
        fade-out: 20


capture-cycle:
  action-bar:
    enabled: true
    text: "&eCapture en cours (&6%time%&e)"
    time:
      use-short-units: true
      format: "%day%%hour%%minute%%second%"
      time-units:
        day: "j"
        hour: "h"
        minute: "m"
        second: "s"
  displays: {}


running-cycle:
  displays: {}

#############################################
###           GENERAL SETTINGS            ###
#############################################

# The spawn of the game. Must have the following format:
# spawn:
#  x: 0
#  y: 0
#  z: 0
#  yaw: 180 (optional, default value is 180)
#  pitch: 0 (optional, default value is 0)
#  world: "world"
game-spawn:
  x: 96.5
  y: 116
  z: 56.5
  yaw: 90
  pitch: 0
  world: "world"

# The list of blocks that players can place outside their base.
# All the blocs are available here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
allowed-blocks:
  - TNT
  - LEVER
  - REDSTONE_TORCH_ON
  - RED_ROSE
  - YELLOW_FLOWER

# A list of blocks which are only placeable in the chest room.
# All the blocs are available here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
vault-blocks:
  - CHEST
  - ENDER_CHEST
  - SHULKER_BOX

# The maximum number of players who can play in the same game.
max-players: 16

# The maximum number of spectators who can join a game.
max-spectators: 8

# Set 'true' if you want eliminated players to be kicked of the server or else set 'false'.
kick-eliminated: false

# Time in seconds before pvp activation.
# Default value is 1800 (30 minutes).
pvp-activation-time: 15

# Time in seconds before assaults activation.
# Default value is 3600 (1 hour).
assaults-activation-time: 30

# The maximum duration in seconds of a game. After this time, the current game
# will be stopped and the remaining teams will be declared equal.
# Default value is 10800 (3 hours).
max-game-duration: 10800

# The duration in seconds of the launch period.
starting-cycle-duration: 1

# Set 'true' if you want to allow friendly fire or else set 'false'.
friendly-fire: false

# The percentage of players needed to capture a base.
catcher-percentage: 50

# Set 'true' if you want players who has slept in a bed to respawn in it or else set 'false'.
allow-bed-respawn: true

#############################################
###             CHAT SETTINGS             ###
#############################################


# All the settings about the chat used during the waiting cycle.
waiting-cycle-chat:
  # Set 'true' if you want to allow players to send messages in the chat
  # or else, set this value to 'false'.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %message% -> The message.
  format: "%player% &r: %message%"


# All the settings about the chat used during a game.
game-chat:
  # Set 'true' if you want to allow players to send messages in the chat
  # or else, set this value to 'false'.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %team_name% -> The name of the player's team.
  # - %message% -> The message.
  format: "%team_name% %player%&r : %message%"


# All the settings about the team chat used during a game.
team-chat:
  # Set 'true' if you want to allow players to send messages in the chat
  # or else, set this value to 'false'.
  enabled: true
  # The prefix set before a message to indicate that it is a team message.
  # Must be a single character like '!' or '@' for example.
  prefix: "@"
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %team_name% -> The name of the player's team.
  # - %message% -> The message.
  format: "%team_name% %player%&r : %message%"


# All the settings about the spectator chat.
spectator-chat:
  # Set 'true' if you want to allow players to send messages in the chat
  # or else, set this value to 'false'.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %message% -> The message.
  format: "&7%player% &r: %message%"
