# FallenKingdom v0.0.1

#############################################
###           GENERAL SETTINGS            ###
#############################################

# Select the language of the plugin. Here is the list of available languages:
# - EN
# - FR
lang: FR

#############################################
###            GAME SETTINGS              ###
#############################################

# The spawn of the game. Must have the following format:
# spawn:
#  x: 0
#  y: 0
#  z: 0
#  yaw: 180 (optional, default value is 180)
#  pitch: 0 (optional, default value is 0)
#  world: "world"
game-spawn:
  x: 96.5
  y: 116
  z: 56.5
  yaw: 90
  pitch: 0
  world: "world"

# The list of blocks that players can place outside their base.
# All the blocs are available here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
allowed-blocks:
  - TNT
  - LEVER
  - REDSTONE_TORCH_ON
  - RED_ROSE
  - YELLOW_FLOWER

# A list of blocks which are only placeable in the chest room.
# All the blocs are available here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
vault-blocks:
  - CHEST
  - ENDER_CHEST
  - SHULKER_BOX

# The minimum number of players required to start a game. Must be greater or equals than 2.
min-players: 2

# The minimum number of players required to start a game automatically. Must be greater or equals than 2.
min-players-for-auto-start: 2

# Set 'true' if you want to allow the plugin to start the game automatically when there is the
# required number of online players. If 'false' is set, the game can only be launched using the
# '/fk start' command.
auto-start: true

# The maximum number of players who can play in the same game.
max-players: 16

# The maximum number of spectators who can join a game.
max-spectators: 8

# Set 'true' if you want eliminated players to be kicked of the server or else set 'false'.
kick-eliminated: false

# Time in seconds before pvp activation.
# Default value is 1800 (30 minutes).
pvp-activation-time: 5

# Time in seconds before assaults activation.
# Default value is 3600 (1 hour).
assaults-activation-time: 10

# Time in seconds before nether activation.
# Default value is 900 (15 minutes).
nether-activation-time: 900

# Time in seconds before end activation.
# Default value is 1800 (30 minutes).
end-activation-time: 1800

# Set 'true' if you want to allow players to go to the nether or else set 'false'.
allow-nether: true

# Set 'true' if you want to allow players to go to the end or else set 'false'.
allow-end: true

# The maximum duration in seconds of a game. After this time, the current game
# will be stopped and the remaining teams will be declared equal.
# Default value is 10800 (3 hours).
max-game-duration: 10800

# The duration in seconds of the launch period.
starting-cycle-duration: 10

# Set 'true' if you want to allow friendly fire or else set 'false'.
friendly-fire: false

# Set 'true' if you want all the players of the team to be eliminated
# when their base is captured. If 'false' is set, players with their
# base captured will be eliminated when they die.
eliminate-on-capture: false

# The percentage of players needed to capture a base.
catcher-percentage: 50

# Set 'true' if you want players who has slept in a bed to respawn in it or else set 'false'.
allow-bed-respawn: true

# The type of capture used. You can choose between two types of capture:
#
# - AREA -> Players have to go into the enemy vaults and to stay in them during
#   a specific amount of time to capture an enemy base.
#
# - NEXUS -> Players have to damage a nexus with a specific amount of life
#   to capture an enemy base.
#
# The default value is 'AREA'.
capture-type: "AREA"

# This section contains all the settings about the capture type 'AREA'.
area-capture:
  # The time in seconds during which a player must stay in a base to capture it.
  capture-duration: 5

#############################################
###             CHAT SETTINGS             ###
#############################################

# All the settings about the chat used during the waiting cycle.
waiting-cycle-chat:
  # Set 'true' if you want to allow players to send messages in the chat
  # or else, set this value to 'false'.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %message% -> The message.
  format: "&e%player% &6: &r%message%"


# All the settings about the chat used during a game.
game-chat:
  # Set 'true' if you want to allow players to send messages in the chat
  # or else, set this value to 'false'.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %team_name% -> The name of the player's team.
  # - %message% -> The message.
  format: "%team_name% %player%&r : %message%"


# All the settings about the team chat used during a game.
team-chat:
  # Set 'true' if you want to allow players to send messages in the chat
  # or else, set this value to 'false'.
  enabled: true
  # The prefix set before a message to indicate that it is a team message.
  # Must be a single character like '!' or '@' for example.
  prefix: "@"
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %team_name% -> The name of the player's team.
  # - %message% -> The message.
  format: "%team_name% %player%&r : %message%"


# All the settings about the spectator chat.
spectator-chat:
  # Set 'true' if you want to allow players to send messages in the chat
  # or else, set this value to 'false'.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %message% -> The message.
  format: "&7%player% &r: %message%"


#############################################
###           COMBAT SETTINGS             ###
#############################################


# This section contains all the settings about the combat module.
combat-module:
  # The duration of a combat between two players. If a player disconnect
  # while he's in combat, he will be automatically killed.
  combat-duration: 15
  # Set 'true' if you want a player to be killed when he disconnects while
  # being in combat or else set 'false'.
  die-on-combat-disconnection: true


#############################################
###           BORDER SETTINGS             ###
#############################################


borders:
  world-border:
    center:
      x: 0
      z: 0
    size: 860
    damages: 100
    world: "world"


#############################################
###                CYCLES                 ###
#############################################


waiting-cycle:
  displays:
    10:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.10.message}"
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.10.subtitle}"
      sound:
        type: "SOUND"
        sound: "NOTE_BASS"
        pitch: 1
    3:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.3.message}"
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 1
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.3.subtitle}"
    2:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.2.message}"
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 1.5
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.2.subtitle}"
    1:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.1.message}"
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 2
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.1.subtitle}"
    0:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.0.message}"
      sound:
        type: "SOUND"
        sound: "LEVEL_UP"
        pitch: 2
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.0.subtitle}"
        stay: 20
        fade-out: 20


game-cycle:
  displays:
    1200:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.1200.message}"
    1500:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.1500.message}"
    1740:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.1740.message}"
    3000:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.3000.message}"
    3300:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.3300.message}"
    3540:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.3540.message}"


#############################################
###               DISPLAYS                ###
#############################################

pvp:
  enabled:
    message:
      type: "MESSAGE"
      text: "${pvp.enabled.message}"
    title:
      type: "TITLE"
      title: "${pvp.enabled.title}"
      subtitle: "${pvp.enabled.subtitle}"
  disabled:
    message:
      type: "MESSAGE"
      text: "${pvp.disabled.message}"
    title:
      type: "TITLE"
      title: "${pvp.disabled.title}"
      subtitle: "${pvp.disabled.subtitle}"


assaults:
  enabled:
    message:
      type: "MESSAGE"
      text: "${assaults.enabled.message}"
    title:
      type: "TITLE"
      title: "${assaults.enabled.title}"
      subtitle: "${assaults.enabled.subtitle}"
  disabled:
    message:
      type: "MESSAGE"
      text: "${assaults.disabled.message}"
    title:
      type: "TITLE"
      title: "${assaults.disabled.title}"
      subtitle: "${assaults.disabled.subtitle}"


team:
  add:
    message:
      type: "MESSAGE"
      text: "${team.add.message}"
  remove:
    message:
      type: "MESSAGE"
      text: "${team.remove.message}"


win:
  all:
    message:
      type: "MESSAGE"
      text: "${win.message}"
  self:
    title:
      type: "TITLE"
      title: "${win.self.title}"
      subtitle: "${win.self.subtitle}"
  other:
    title:
      type: "TITLE"
      title: "${win.other.title}"
      subtitle: "${win.other.subtitle}"


on-base-capture-start:
  self:
    message:
      type: "MESSAGE"
      text: "${capture.start.self.message}"
  captured-team:
    message:
      type: "MESSAGE"
      text: "${capture.start.captured-team.message}"


on-base-capture-stop:
  self:
    message:
      type: "MESSAGE"
      text: "${capture.stop.self.message}"
  captured-team:
    message:
      type: "MESSAGE"
      text: "${capture.stop.captured-team.message}"


on-base-captured:
  self:
    message:
      type: "MESSAGE"
      text: "${capture.base-captured.self.message}"
  other:
    message:
      type: "MESSAGE"
      text: "${capture.base-captured.other.message}"
  captured-team:
    message:
      type: "MESSAGE"
      text: "${capture.base-captured.captured-team.message}"
    title:
      type: "TITLE"
      title: "${capture.base-captured.captured-team.title}"
      subtitle: "${capture.base-captured.captured-team.subtitle}"