# FallenKingdom v0.0.1

#############################################
###                MESSAGES               ###
#############################################

# This section is about the '/fk' command.
command-fk:
  # Message sent to the sender when he doesn't have the permission to execute the command.
  no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
  # This section is about the '/fk start' command.
  start:
    # Message sent to the sender when he doesn't have the permission to execute the command.
    no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
  # This section is about the '/fk stop' command.
  stop:
    # Message sent to the sender when he doesn't have the permission to execute the command.
    no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
  # This section is about the '/fk pvp' command.
  pvp:
    # Message sent to the sender when he doesn't have the permission to execute the command.
    no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
    # Message sent to the sender when he's trying to enable / disable pvp when no game is running.
    game-not-running: "&c>> La partie n'a pas encore commencé."
    # Message sent to the sender when he's trying to enable pvp when it already is.
    already-enabled: "&c>> Le pvp est déjà activé."
    # Message sent to the sender when he's trying to disable pvp when it already is.
    already-disabled: "&c>> Le pvp est déjà désactivé."
  # This section is about the '/fk assaults' command.
  assaults:
    # Message sent when the sender doesn't have the permission to execute the command.
    no-permission: "&c>> Vous n'avez pas la permission d'utiliser cette commande."
    # Message sent to the sender when he's trying to enable / disable assaults when no game is running.
    game-not-running: "&c>> La partie n'a pas encore commencé."
    # Message sent to the sender when he's trying to enable assaults when they already are.
    already-enabled: "&c>> Les assaults sont déjà activés."
    # Message sent to the sender when he's trying to disable assaults when they already are.
    already-disabled: "&c>> Les assaults sont déjà désactivés."


# This section is about the pvp.
pvp:
  # Message sent to all the online players when pvp is enabled.
  enabled: "&6>> &eLe pvp est désormais &aactivé&e."
  # Message sent to all the online players when pvp is disabled.
  disabled: "&6>> &eLe pvp est désormais &cdésactivé&e."


# This section is about the assaults.
assaults:
  # Message sent to all the online players when assaults are enabled.
  enabled: "&6>> &eLes assaults sont désormais &aautorisés&e."
  # Message sent to all the online players when assaults are disabled.
  disabled: "&6>> &eLes assaults sont désormais &cinterdits&e."


# This section is about the waiting cycle.
game-waiting:
  # This section contains all the messages sent during the waiting cycle.
  messages:
    # Message sent when a player joins the game.
    join: "&6%player% &ea rejoint la partie."
    # Message sent when a player leaves the game.
    quit: "&6%player% &ea quitté la partie."


# This section contains all the configuration of the starting cycle.
game-starting:
  # This section is about the timer started before starting the game.
  timer:
    # The duration of the timer in seconds.
    duration: 10


spawn:
  x: 96.5
  y: 116
  z: 56.5
  yaw: 90
  pitch: 0
  world: "world"


messages:
  1:
    type: "TITLE"
    title: "My title"
    subtitle: "My subtitle"
  2:
    type: "TEXT"
    text: "My text"
  3:
    type: "TEXT"
    text:
      - "line1"
      - "line2"
  4:
    type: "ACTIONBAR"
    text: "My text"