# FallenKingdom v0.0.1

#############################################
###           GENERAL SETTINGS            ###
#############################################

# Select the language of the plugin.
# Available values: FR, EN.
#
# If your language isn't supported, you can add it by yourself. To do that,
# make a copy of the default language file and rename it using the following
# format: 'lang_<lang>.yml'. Then, put it in the 'langs' folder set it as the
# selected language. To finish, just edit the texts of the file.
#
# Example: You want to add German as a new language. The name of the lang file
# will be 'lang_GE.yml' and the selected language will be 'GE'.
lang: FR

#############################################
###            GAME SETTINGS              ###
#############################################

# The spawn of the game. Must have the following format:
# spawn:
#  x: 0
#  y: 0
#  z: 0
#  yaw: 180 (optional, default value is 180)
#  pitch: 0 (optional, default value is 0)
#  world: "world"
game-spawn:
  x: 96.5
  y: 116
  z: 56.5
  yaw: 90
  pitch: 0
  world: "world"

# The list of blocks that players can place outside their base.
# Available values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
allowed-blocks:
  - TNT
  - LEVER
  - REDSTONE_TORCH_ON
  - RED_ROSE
  - YELLOW_FLOWER

# A list of blocks which are only placeable in the chest room.
# Available values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
vault-blocks:
  - CHEST
  - ENDER_CHEST
  - SHULKER_BOX

# The minimum number of players required to start a game.
# Available values: A number >= 2.
min-players: 2

# The minimum number of players required to start a game automatically.
# Available values: A number >= 2.
min-players-for-auto-start: 2

# Enable / Disable the automatic game start. If disabled, the game can only be launched using
# the '/fk start' command.
# Available values: true / false.
auto-start: true

# The maximum number of players who can play in the same game.
# Available values: A number >= 2.
max-players: 16

# The maximum number of spectators who can join a game.
# Available values: A number >= 0.
max-spectators: 8

# Kick players when they are eliminated.
# Available values: true / false.
kick-eliminated: false

# Enable / Disable the Nether.
# Available values: true / false.
allow-nether: true

# Enable / Disable the End.
# Available values: true / false.
allow-end: true

# Time in seconds before pvp activation.
# Available values: A number >= 0.
# Default value: 1800 (30 minutes).
pvp-activation-time: 5

# Time in seconds before assaults activation.
# Available values: A number >= 0.
# Default value: 3600 (1 hour).
assaults-activation-time: 10

# Time in seconds before nether activation.
# Available values: A number >= 0.
# Default value: 900 (15 minutes).
# Note: Nether will not be enabled if 'allow-nether' is set to 'false'.
nether-activation-time: 15

# Time in seconds before end activation.
# Available values: A number >= 0.
# Default value: 1800 (30 minutes).
# Note: End will not be enabled if 'allow-end' is set to 'false'.
end-activation-time: 30

# The maximum duration in seconds of a game. After this time, the current game
# will be stopped and the remaining teams will be declared equal.
# Available values: A number >= 0.
# Default value: 10800 (3 hours).
max-game-duration: 10800

# The duration in seconds of the launch period.
# Available values: A number >= 0.
starting-cycle-duration: 10

# Enable / Disable friendly fire.
# Available values: true / false.
friendly-fire: false

# Set all the players of a team to be eliminated when their base is captured.
# If disabled, players with their base captured will be eliminated when they die.
# Available values: true / false.
eliminate-on-capture: false

# The percentage of players needed to capture a base.
catcher-percentage: 50

# If enabled, players who as slept in a bed will respawn in it. If they have no bed,
# players will respawn at the spawn of their base.
# Available values: true / false.
allow-bed-respawn: true

# Enable / Disable the action bar displayed during a game. This action bar will display to players
# directions to go to the spawn or to their base.
# Available values: true / false.
game-action-bar: true

# The type of capture used. You can choose between two types of capture:
#
# - AREA -> Players have to go into the enemy vaults and to stay in them during
#   a specific amount of time to capture an enemy base.
#
# - NEXUS -> Players have to damage a nexus with a specific amount of life
#   to capture an enemy base.
#
# Available values: AREA (NEXUS is not yet implemented).
# Default value is 'AREA'.
capture-type: "AREA"

# This section contains all the settings about the capture type 'AREA'.
area-capture:
  # The time in seconds during which a player must stay in a base to capture it.
  # Available values: A number >= 0.
  # Default value: 60 (1 minute).
  capture-duration: 5

#############################################
###             CHAT SETTINGS             ###
#############################################

# All the settings about the chat used during the waiting cycle.
waiting-cycle-chat:
  # Enable / Disable the chat.
  # Available values: true / false.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %message% -> The message.
  format: "&e%player% &6: &r%message%"


# All the settings about the chat used during a game.
game-chat:
  # Enable / Disable the chat.
  # Available values: true / false.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %team_name% -> The name of the player's team.
  # - %message% -> The message.
  format: "%team_name% %player%&r : %message%"


# All the settings about the team chat used during a game.
team-chat:
  # Enable / Disable the chat.
  # Available values: true / false.
  enabled: true
  # The prefix set before a message to indicate that it is a team message.
  # Must be a single character like '!' or '@' for example.
  prefix: '@'
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %team_name% -> The name of the player's team.
  # - %message% -> The message.
  format: "%team_name% %player%&r : %message%"


# All the settings about the spectator chat.
spectator-chat:
  # Enable / Disable the chat.
  # Available values: true / false.
  enabled: true
  # The chat format. You can use the following placeholders:
  # - %player% -> The player's name.
  # - %display_name% -> The player's display name.
  # - %message% -> The message.
  format: "&7%player% &r: %message%"


#############################################
###           COMBAT SETTINGS             ###
#############################################


# This section contains all the settings about the combat module.
combat-module:
  # The duration of a combat between two players. If a player disconnect
  # while he's in combat, he will be automatically killed.
  # Available values: A number >= 0.
  combat-duration: 15
  # Make a player to be killed when he disconnected while being in combat.
  # Available values: true / false.
  die-on-combat-disconnection: true


#############################################
###           BORDER SETTINGS             ###
#############################################


# This section contains all the settings about world borders. To add a new
# border for a specific world, you must use the following format:
#
# An id for the border in config. Use what you want.
# my-world-border:
#  # The center of the border (optional).
#  # Default value: (0,0).
#  center:
#    x: 0
#    y: 0
#  # The size of the border (optional).
#  # Available values: A positive number.
#  # Default value: max border size.
#  size: 1000
#  # The number of damages of the border (optional).
#  # Available values: A positive number.
#  # Default value: 0.2.
#  damages: 5
#  # The distance for which a player doesn't take damages when he's outside of the border.
#  # Available values: A positive number.
#  # Default value: 5.
#  safe-zone-distance: 10
#  # The warning time of the border.
#  # Available values: A positive number.
#  # Default value: 15
#  warning-time: 30
#  # The warning distance of the border. When a player is closest the border, a red border
#  # will appear on his screen until he moves away.
#  # Available values: A positive number.
#  # Default value: 5
#  warning-distance: 10
#  # The world in which set the border.
#  world: "my-world"
borders:
  world-border:
    center:
      x: 0
      z: 0
    size: 860
    damages: 100
    world: "world"


#############################################
###           WEATHER SETTINGS            ###
#############################################


# This section contains all the settings about the weather. To configure
# the weather of a specific world, you have to use the following format:
#
# # The name of the section. Use what you want.
# my-world:
#  # The world in which set the weather.
#  world: "my-world"
#  # The weather to set in the world.
#  # Available values: NORMAL, SUNNY, RAIN, STORM.
#  weather: "SUNNY"
weathers:
  world:
    world: "world"
    weather: "SUNNY"


#############################################
###               DISPLAYS                ###
#############################################


waiting-cycle:
  displays:
    10:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.10.message}"
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.10.subtitle}"
      sound:
        type: "SOUND"
        sound: "NOTE_BASS"
        pitch: 1
    3:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.3.message}"
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 1
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.3.subtitle}"
    2:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.2.message}"
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 1.5
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.2.subtitle}"
    1:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.1.message}"
      sound:
        type: "SOUND"
        sound: "NOTE_PIANO"
        pitch: 2
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.1.subtitle}"
    0:
      message:
        type: "MESSAGE"
        text: "${waiting-cycle.timer.0.message}"
      sound:
        type: "SOUND"
        sound: "LEVEL_UP"
        pitch: 2
      title:
        type: "TITLE"
        subtitle: "${waiting-cycle.timer.0.subtitle}"
        stay: 20
        fade-out: 20


game-cycle:
  displays:
    1200:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.1200.message}"
    1500:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.1500.message}"
    1740:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.1740.message}"
    3000:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.3000.message}"
    3300:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.3300.message}"
    3540:
      message:
        type: "MESSAGE"
        text: "${game-cycle.timer.3540.message}"


pvp:
  enabled:
    message:
      type: "MESSAGE"
      text: "${pvp.enabled.message}"
    title:
      type: "TITLE"
      title: "${pvp.enabled.title}"
      subtitle: "${pvp.enabled.subtitle}"
  disabled:
    message:
      type: "MESSAGE"
      text: "${pvp.disabled.message}"
    title:
      type: "TITLE"
      title: "${pvp.disabled.title}"
      subtitle: "${pvp.disabled.subtitle}"


assaults:
  enabled:
    message:
      type: "MESSAGE"
      text: "${assaults.enabled.message}"
    title:
      type: "TITLE"
      title: "${assaults.enabled.title}"
      subtitle: "${assaults.enabled.subtitle}"
  disabled:
    message:
      type: "MESSAGE"
      text: "${assaults.disabled.message}"
    title:
      type: "TITLE"
      title: "${assaults.disabled.title}"
      subtitle: "${assaults.disabled.subtitle}"


nether:
  enabled:
    message:
      type: "MESSAGE"
      text: "${nether.enabled.message}"
    title:
      type: "TITLE"
      title: "${nether.enabled.title}"
  disabled:
    message:
      type: "MESSAGE"
      text: "${nether.disabled.message}"
    title:
      type: "TITLE"
      title: "${nether.disabled.title}"


end:
  enabled:
    message:
      type: "MESSAGE"
      text: "${end.enabled.message}"
    title:
      type: "TITLE"
      title: "${end.enabled.title}"
  disabled:
    message:
      type: "MESSAGE"
      text: "${end.disabled.message}"
    title:
      type: "TITLE"
      title: "${end.disabled.title}"


team:
  add:
    message:
      type: "MESSAGE"
      text: "${team.add.message}"
  remove:
    message:
      type: "MESSAGE"
      text: "${team.remove.message}"


win:
  all:
    message:
      type: "MESSAGE"
      text: "${win.message}"
  self:
    title:
      type: "TITLE"
      title: "${win.self.title}"
      subtitle: "${win.self.subtitle}"
  other:
    title:
      type: "TITLE"
      title: "${win.other.title}"
      subtitle: "${win.other.subtitle}"


on-base-capture-start:
  self:
    message:
      type: "MESSAGE"
      text: "${capture.start.self.message}"
  captured-team:
    message:
      type: "MESSAGE"
      text: "${capture.start.captured-team.message}"


on-base-capture-stop:
  self:
    message:
      type: "MESSAGE"
      text: "${capture.stop.self.message}"
  captured-team:
    message:
      type: "MESSAGE"
      text: "${capture.stop.captured-team.message}"


on-base-captured:
  self:
    message:
      type: "MESSAGE"
      text: "${capture.base-captured.self.message}"
  other:
    message:
      type: "MESSAGE"
      text: "${capture.base-captured.other.message}"
  captured-team:
    message:
      type: "MESSAGE"
      text: "${capture.base-captured.captured-team.message}"
    title:
      type: "TITLE"
      title: "${capture.base-captured.captured-team.title}"
      subtitle: "${capture.base-captured.captured-team.subtitle}"